### PR TITLE
Solve the Tug of War example problem using both Pycollo and opty

### PR DESCRIPTION
**Pull request by brocksam**
Here's the OCP we're solving here: https://peerj.com/articles/1638/

Video (not mine) here: https://www.youtube.com/watch?v=s6NJEHRDoVs

# Model

Both solver here using the rigid tendon model and first-order activation dynamics.

# Using Pycollo

Transcription: 8th-order LGL-IIIA w/ 100 mesh sections
Optimal cost: 0.0526

Screenshot 2023-08-23 at 10 27 53

Screenshot 2023-08-23 at 10 27 57

Screenshot 2023-08-23 at 10 28 03

Screenshot 2023-08-23 at 10 28 06

Screenshot 2023-08-23 at 10 28 09

# Using opty

Transcription: 1st-order LGR-IIA (backwards Euler) w/ 10,000 mesh sections
Optimal cost: 0.0574

Screenshot 2023-08-23 at 10 19 42

Screenshot 2023-08-23 at 10 19 46

Screenshot 2023-08-23 at 10 19 49

Screenshot 2023-08-23 at 10 19 53

Screenshot 2023-08-23 at 10 19 56

### CODE REVIEW

**Comment by brocksam** [comment]
Really pleased with the agreement in the results between the two. Good confirmation that the models in `sympy.physics._biomechanics` are behaving nicely too.

**Comment by moorepants** [comment]
Wow, surprised that opty did it! Very cool!

**Comment by brocksam** [comment]
> Wow, surprised that opty did it! Very cool!

And on such a dense mesh too. Didn't see the memory issues that you were seeing yesterday on the large problem. Mind you, the dynamics here are very simple.

Working on this with elastic musculotendon's now.

**Comment by moorepants** [comment]
Any idea what the odd parts of the opty muscle excitations are?

**Comment by moorepants** [comment]
FYI, some notes on the opty issue I encountered with the large # nodes: https://github.com/csu-hmc/opty/issues/100

**Pull request merged**
